name: ARMv8_Build_Full

on:
  repository_dispatch:
  workflow_dispatch:
#  release:
#    types: published
  schedule:
    - cron: 0 0 * * *
  watch:
    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part3.sh
  MRG_ADD_SH: aarch64/ARMv8.sh
  Update_Ver_SH: aarch64/autoVersion.sh
#   SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  TZ: Asia/Shanghai
  FILE_NAME: ARMv8_Full
  PRODUCT_NAME: ARMv8_Full
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    #- name: WeChat notification
    #  run: curl https://sc.ftqq.com/${{ secrets.ServerChan }}.send?text=${{ env.FILE_NAME }}开始编译
      
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo -E apt-get -qq install rename
        sudo -E apt-get -qq install pigz
        sudo -E apt-get -qq install time
        sudo -E apt-get -qq install sshpass
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H")
        echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "DATE1=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
#        echo "::set-env name=useVersionInfo::$useVersionInfo"
#        echo "::set-env name=DATE::$(date "+%Y-%m-%d %H:%M:%S")"

    - name: Build firmware
      id: build
      run: |
        echo $PWD
        sudo mkdir /opt/kernel
        sudo cp $GITHUB_WORKSPACE/BuildARMv8/*.*/*.tar.gz /opt/kernel/
        #sudo cp $GITHUB_WORKSPACE/BuildARMv8/mk_*.tar.gz /opt/
        #sudo tar xvzf mk_*.tar.gz
        cd /opt
        sudo cp $GITHUB_WORKSPACE/scripts/respawn_mks.sh ./
        sudo git clone https://github.com/unifreq/openwrt_packit openwrt
        sudo chmod +x ./respawn_mks.sh
        sudo ./respawn_mks.sh
        cd /opt/openwrt
        sudo wget $(curl -s https://api.github.com/repos/rq1025330/Actions-OP/releases/53780481 | grep browser_download_url | cut -d '"' -f 4)
        chmod +x $GITHUB_WORKSPACE/$Update_Ver_SH
        sudo $GITHUB_WORKSPACE/$Update_Ver_SH
        sudo cp $GITHUB_WORKSPACE/scripts/whoami ./
        #sudo ./mk_rk3328_beikeyun.sh
        #sudo ./mk_rk3328_beikeyun_basic.sh
        #sudo ./mk_rk3328_beikeyun_plus.sh
        #sudo ./mk_rk3328_beikeyun_plusplus.sh
        #sudo ./mk_rk3328_beikeyun_plusplusplus.sh
        #sudo ./mk_rk3328_l1pro.sh
        #sudo ./mk_rk3328_l1pro_basic.sh
        #sudo ./mk_rk3328_l1pro_plus.sh
        #sudo ./mk_rk3328_l1pro_plusplus.sh
        #sudo ./mk_rk3328_l1pro_plusplusplus.sh
        #sudo ./mk_s905d_n1.sh
        sudo ./mk_s905d_n1_basic.sh
        sudo ./mk_s905d_n1_plus.sh
        sudo ./mk_s905d_n1_plusplus.sh
        sudo ./mk_s905d_n1_plusplusplus.sh
        #sudo ./mk_s905x2_x96max.sh
        #sudo ./mk_s905x2_x96max_basic.sh
        #sudo ./mk_s905x2_x96max_plus.sh
        #sudo ./mk_s905x2_x96max_plusplus.sh
        #sudo ./mk_s905x2_x96max_plusplusplus.sh
        #sudo ./mk_s905x3_multi.sh
        sudo ./mk_s905x3_multi_basic.sh
        sudo ./mk_s905x3_multi_plus.sh
        sudo ./mk_s905x3_multi_plusplus.sh
        sudo ./mk_s905x3_multi_plusplusplus.sh
        #sudo ./mk_s912_zyxq.sh
        #sudo ./mk_s912_zyxq_basic.sh
        #sudo ./mk_s912_zyxq_plus.sh
        #sudo ./mk_s912_zyxq_plusplus.sh
        #sudo ./mk_s912_zyxq_plusplusplus.sh
        #sudo ./mk_s922x_gtking.sh
        #sudo ./mk_s922x_gtking_basic.sh
        #sudo ./mk_s922x_gtking_plus.sh
        #sudo ./mk_s922x_gtking_plusplus.sh
        #sudo ./mk_h6_vplus.sh
        #sudo ./mk_h6_vplus_basic.sh
        #sudo ./mk_h6_vplus_plus.sh
        #sudo ./mk_h6_vplus_plusplus.sh
        #sudo ./mk_h6_vplus_plusplusplus.sh
        #sudo cp ./*AllPackages.tar.gz ./output/
        #sudo cp ./F-AllPackages.tar.gz ./output/
        #sudo cp ./SF-AllPackages.tar.gz ./output/
        sudo cp ./Full-AllPackages.tar.gz ./output/
        #sudo cp ./files/update*.sh ./output/
        sudo cp files/openwrt-install-amlogic output/openwrt-install-amlogic
        sudo cp files/openwrt-update-amlogic output/openwrt-update-amlogic
        echo "::set-output name=status::success"

    - name: Organize files
      id: organize
      if: steps.build.outputs.status == 'success' && !cancelled()
      run: |
        cd /opt/openwrt/output/
        pigz -9 -p $(nproc) *.img

        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin/targets/*/*/bin.tar.gz

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: env.UPLOAD_FIRMWARE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Create release
      id: release
      uses: ncipollo/release-action@v1
      with:
        name: R${{ env.DATE }} for ${{ env.FILE_NAME }}
        allowUpdates: true
        tag: ${{ env.FILE_NAME }}
        commit: master
        token: ${{ secrets.RELEASES_TOKEN }}
        body: |
          默认IP：192.168.123.1 默认密码：password
          Full版：大全版
          当前使用版本:【编译前的最后一次[➦主源码](https://github.com/coolsnowwolf/lede)更新记录】
          参见 Files4Build 内记录
          **Lite版**---->[下载](https://github.com/rq1025330/Actions-OpenWrt/releases/tag/ARMv8_Lite)
          
          使用luci插件或脚本命令操作方法：
          在系统——晶晨宝盒——在线下载更新——插件更新，（更新固件/内核，备份恢复配置，快照管理等脚本）
          
          ssh中使用命令操作，方法如下：
          安装openwrt命令：
          1.amlogic s9xxx 系列盒子安装命令：openwrt-install-amlogic
          
          更新openwrt命令：
          1.先上传盒子对应的openwrt固件、openwrt-update-*到/mnt/mmcblk*p4/目录下，支持直接上传并使用压缩文件，格式支持：img / .img.gz / img.xz / .7z / .zip
          2. amlogic s9xxx 系列盒子更新命令：openwrt-update-amlogic
          3. Chainedbox L1Pro和BeikeYun盒子更新命令：openwrt-update-rockchip
          4.v-plus盒子更新命令：openwrt-update-allwinner
          
          更新内核命令：
          1.先上传盒子对应的相关内核的3个文件到/mnt/mmcblk*p4/目录下
          2.更新命令：openwrt-kernel
          
          备份/恢复配置，快照管理命令：flippy 或 openwrt-backup 根据菜单提示选择相关操作。
  
        artifacts: ${{ env.FIRMWARE }}/*
    
    - name: Telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          编译时间：${{ env.DATE }}
          lede更新信息：${{ env.useVersionInfo }}
          ${{ env.PRODUCT_NAME }}打包完成
